service: sls-boilerplate

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: lib/handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
          authorizer: auth

  auth:
    handler: lib/handler.auth
package:
  individually: true

plugins:
  - serverless-webpack